version: "3.8"

services:
  app:
    container_name: ${APP_NAME}
    image: interactive_terminal_gui_development
    build:
      context: Docker/Development
    volumes:
      - .:./application
    ports:
      - 3000:3000
